version: "3.8"

services:
  # eureka
  eureka:
    image: tuananh2582000/eureka
    container_name: eureka
    ports:
      - "8761:8761"
    environment:
      eureka.instance.hostname: 209.97.160.50
      eureka.client.serviceUrl.defaultZone: http://209.97.160.50:8761/eureka/
    networks:
      - microservice
  # api-getway
  gateway:
    image: tuananh2582000/gateway
    container_name: gateway
    ports:
      - "9191:9191"
    depends_on:
      - eureka
    environment:
      eureka.client.service-url.defaultZone: http://eureka:8761/eureka/
    networks:
      - microservice
  # cloud server
  cloud-server:
    image: tuananh2582000/cloud-server
    container_name: cloud-server
    ports:
      - "8888:8888"
    environment:
      spring.cloud.config.server.git.default-label: main
    networks:
      - microservice

  # my sql
  db:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: diem66
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - microservice

  # user-service
  user-service:
    image: tuananh2582000/user-service
    container_name: user-service
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/userdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: diem66
      eureka.client.service-url.defaultZone: http://eureka:8761/eureka/
      eureka.client.instance: 209.97.160.50
    networks:
      - microservice

  # note-service:
  note-service:
    image: tuananh2582000/note-service
    container_name: note-service
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/notedb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: diem66
      eureka.client.service-url.defaultZone: http://eureka:8761/eureka/
      eureka.client.instance: 209.97.160.50
    networks:
      - microservice

  frontend:
    stdin_open: true
    tty: true
    image: tuananh2582000/note-reactjs:v1
    ports:
      - "80:80"
    networks:
      - microservice
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
networks:
  microservice:
